server.port=8080

# --- Auth Service Route ---
spring.cloud.gateway.routes[0].id=auth-service
# Use the service name from docker-compose
spring.cloud.gateway.routes[0].uri=http://auth-service:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/api/auth/(?<segment>.*), /auth/${segment}

# --- Inventory Service Route ---
spring.cloud.gateway.routes[1].id=inventory-service
# Use the service name from docker-compose
spring.cloud.gateway.routes[1].uri=http://inventory-service:8083
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/products/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/api/products/(?<segment>.*), /products/${segment}

# --- Notification Service Route ---
spring.cloud.gateway.routes[2].id=notification-service
# Use the service name from docker-compose
spring.cloud.gateway.routes[2].uri=http://notif-service:8082
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/notifications/**
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/api/notifications/(?<segment>.*), /notifications/${segment}